type Query {
  allUsers: [User]
  allHRAdvisors: [HRAdvisor]
  allEmployees: [Employee]
}

type Mutation {
  testMutation(message: String!): String

  createHRAdvisor(hr: CreateHRAdvisorInput!): HRAdvisor
  createEmployee(employee: CreateEmployeeInput!): Employee

  updateHRAdvisor(
    immatriculation: ID!
    hr: UpdateHRAdvisorInput
  ): HRAdvisor
  updateEmployee(immatriculation: ID!, employee: UpdateEmployeeInput): Employee

  deleteUser(immatriculation: ID!): deletedUserResponse
}

interface deletedUserResponse {
  success: Boolean!
  message: String
}

interface User {
  immatriculation: ID!
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
}

type HRAdvisor implements User {
  immatriculation: ID!
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
  department: String
}

type Employee implements User {
  immatriculation: ID!
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
  jobTitle: String
  jobDescription: String
  contractType: String
}

input CreateHRAdvisorInput {
  email: String!
  firstname: String!
  lastname: String!
  phone: String!
  role: String!
  department: String!
}

input CreateEmployeeInput {
  email: String!
  firstname: String!
  lastname: String!
  phone: String!
  role: String!
  jobTitle: String!
  jobDescription: String!
  contractType: String!
}



input UpdateHRAdvisorInput {
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
  department: String
}

input UpdateEmployeeInput {
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
  jobTitle: String
  jobDescription: String
  contractType: String
}
