scalar Date

type Query{
    allInsurances: [Insurance]
    findOneInsurance(idInsurance: ID!): Insurance
}
type Mutation{
    createInsurance(insurance: CreateInsuranceInput!): Insurance
    updateInsurance(idInsurance: ID!, insurance: UpdateInsuranceInput): Insurance
    deleteInsurance(idInsurance: ID!): DeletedInsuranceResponse!
}

type Insurance {
    idInsurance: ID!
    idEmployee: ID!
    idHRAdvisor: ID!
    insurance_end_date: Date!
    insuranceDescription: String!
    beneficiary: String!
}
input CreateInsuranceInput {
    idEmployee: ID!
    idHRAdvisor: ID!
    insurance_end_date: Date!
    insuranceDescription: String!
    beneficiary: String!
}
input UpdateInsuranceInput {
    idHRAdvisor: ID
    insuranceDescription: String
    beneficiary: String
}
type DeletedInsuranceResponse {
  success: Boolean!
  message: String
}